
version: "3.10"

services:

  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
    networks:
      - app_network
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $DB_NAME -U $DB_PASS"]
      interval: 10s
      timeout: 3s
      retries: 5

  app:
    container_name: application
    build:
      context: .
      dockerfile: Dockerfile

    networks:
      - app_network
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy

networks:
  app_network:
    name: app_network

